Introduction documentation reworked
ubports/docs.ubports.com pull request #396
Opened 2021-03-12 19:14 UTC by comradekingu

2021-03-13 10:13 UTC, doniks requested changes

2021-03-13 10:13 UTC, doniks commented on about/introduction.rst
> +Intro
mhm ... the full in the header please

2021-03-13 11:50 UTC, comradekingu commented on about/introduction.rst
> +Intro
```suggestion
Introduction
```

2021-03-14 07:57 UTC, doniks approved these changes

2021-03-14 07:58 UTC, merged