Update Anbox instructions for OTA-16
ubports/docs.ubports.com pull request #400
Opened 2021-03-12 22:56 UTC by UniversalSuperBox

After OTA-16 (releasing Monday), there is no need to install anbox via apt any more. Some devices do still need a manual kernel install, though.

2021-03-13 04:33 UTC, doniks requested changes

2021-03-13 04:33 UTC, doniks commented on userguide/dailyuse/anbox.rst
>  You will need the device codename and the name of your boot partition for the installation.
this sentence can be removed

2021-03-13 11:59 UTC, comradekingu commented on userguide/dailyuse/anbox.rst
> +- Meizu Pro 5
```suggestion
- Meizu PRO 5
```
As per https://en.wikipedia.org/wiki/Meizu_PRO_5 and https://www.meizu.com/en/products/pro5/spec.html

2021-03-13 12:00 UTC, comradekingu commented on userguide/dailyuse/anbox.rst
> +- BQ M10 HD
```suggestion
- BQ Aquaris M10 HD
```

2021-03-13 12:00 UTC, comradekingu commented on userguide/dailyuse/anbox.rst
> +- BQ M10 FHD
```suggestion
- BQ Aquaris M10 FHD
```

2021-03-13 12:01 UTC, comradekingu commented on userguide/dailyuse/anbox.rst
> +    You now have an adb server running inside your phone. This guide asks you to run some ``adb`` commands, sometimes on your computer, other times on your phone. Carefully check on which device you
```suggestion
    You now have an ADB server running on your Ubuntu Touch device. This guide asks you to run some ``adb`` commands, sometimes on your computer, other times on the device itself. Carefully check which device you are on!
```

2021-03-13 12:02 UTC, comradekingu commented on userguide/dailyuse/anbox.rst
>  You can check that adb server is correctly running locally on your phone by opening the terminal app and enter ``adb devices``. You should see something like::
```suggestion
You can check that ADB server is correctly running locally on your phone by opening the terminal app and enter ``adb devices``. You should see something like::
```

2021-03-13 12:02 UTC, comradekingu commented on userguide/dailyuse/anbox.rst
>  - When you want to install an apk but get the error ``Invalid APK file`` that error could also mean "file not found"
```suggestion
- When you want to install an APK, but get the error ``Invalid APK file`` that error could also mean "file not found"
```

2021-03-13 12:03 UTC, comradekingu commented on userguide/dailyuse/anbox.rst
>    - Check that you typed the file name correctly
```suggestion
  - Check that you typed the filename correctly
```

2021-03-13 13:55 UTC, doniks commented
A note wrt throughput. While I agree content wise with all your review remarks, I try to be mindful of the workload I put specifically on the UT lead developer. Also keeping the release on Mon in mind, I am happy to merge a simpler version of these changes quickly. And I will probably do just that and merge tomorrow, Sunday, either way. We can fill in the fine print afterwards.

2021-03-13 20:19 UTC, UniversalSuperBox commented
It's no problem. Let me make those changes.

2021-03-14 07:52 UTC, doniks approved these changes

2021-03-14 16:19 UTC, merged