PPA documentation language reworked
ubports/docs.ubports.com pull request #405
Opened 2021-03-15 13:39 UTC by comradekingu

2021-03-15 13:39 UTC, comradekingu commented on about/process/ppa.rst
> +Native packages are repositories which contain a ``DEBIAN/`` folder **with** the source used to create the Debian source package (``.dsc``).
This is what it is with regular Debian packages anyway.

2021-03-15 13:40 UTC, comradekingu commented on about/process/ppa.rst
> +Non-standard PPAs (i.e. not ``vivid`, ``xenial``, ` or ``bionic``) are kept for three months.
```suggestion
Non-standard PPAs (i.e. not ``vivid``, ``xenial``, or ``bionic``) are kept for three months.
```

2021-03-15 13:40 UTC, comradekingu commented on about/process/ppa.rst
> +Non-standard PPAs (i.e. not ``vivid`, ``xenial``, ` or ``bionic``) are kept for three months.
```suggestion
Non-standard PPAs (i.e. not ``vivid`, ``xenial``, or ``bionic``) are kept for three months.
```

2021-03-15 13:41 UTC, comradekingu commented on about/process/ppa.rst
> +If they need to be kept for longer, a file with the name ``ubports.keep`` containing a date in the form of in the form of ``YYYY-MM-dd` can be used to decide how long to keep the PPA in the repositor
```suggestion
If they need to be kept for longer, a file with the name ``ubports.keep`` containing a date in the form of in the form of ``YYYY-MM-dd`` can be used to decide how long to keep the PPA in the repository for.
```

2021-03-15 13:43 UTC, comradekingu commented on about/process/ppa.rst
> +Packaging repositories contain a ``debian/`` directory **without** the source used to create the Debian source package (``.dsc``).
```suggestion
Packaging repositories contain a ``DEBIAN`` folder **without** the source used to create the Debian source package (``.dsc``).
```

2021-03-15 13:47 UTC, comradekingu commented on about/process/ppa.rst
> +Native packages are repositories which contain a ``DEBIAN/`` folder **with** the source used to create the Debian source package (``.dsc``).
```suggestion
Native packages are repositories which contain a ``DEBIAN/`` folder **with** the source used to create the DEB source package (``.dsc``).
```

2021-03-15 13:48 UTC, comradekingu commented on about/process/ppa.rst
>  New PPAs can be created dynamically by the CI server using a special :doc:`git-branch naming convention <branch-naming>`. The name of the branch translates literally to the name of the PPA: ``http://
```suggestion
New PPAs can be created dynamically by the CI server using a special :doc:`git-branch naming convention <branch-naming>`. The name of the branch translates literally to the name of the PPA: ``https://repo.ubports.com/dists/[branch name]``
```

2021-03-16 03:37 UTC, doniks requested changes

2021-03-16 03:37 UTC, doniks commented on about/process/ppa.rst
> +Native packages are repositories which contain a ``DEBIAN/`` folder **with** the source used to create the DEB source package (``.dsc``).
lower case I think e.g., https://github.com/ubports/system-settings also below

2021-03-16 03:37 UTC, doniks commented on about/process/ppa.rst
> +Packaging repositories contain a ``DEBIAN`` folder **without** the source used to create the Debian source package (``.dsc``).
like this I think https://github.com/ubports/pulseaudio-packaging . maybe good to add these examples acutally

2021-03-20 03:41 UTC, comradekingu commented on about/process/ppa.rst
> +Native packages are repositories which contain a ``DEBIAN/`` folder **with** the source used to create the DEB source package (``.dsc``).
```suggestion
Native packages are repositories which contain a ``debian/`` folder **with** the source used to create the DEB source package (``.dsc``).
```

2021-03-20 03:42 UTC, comradekingu commented on about/process/ppa.rst
> +Packaging repositories contain a ``DEBIAN`` folder **without** the source used to create the Debian source package (``.dsc``).
```suggestion
Packaging repositories contain a ``debian`` folder **without** the source used to create the Debian source package (``.dsc``).
```

2021-03-21 11:17 UTC, doniks approved these changes

2021-03-21 11:17 UTC, merged