Style improvements
ubports/docs.ubports.com pull request #438
Opened 2021-06-18 07:47 UTC by capsia37

Hello!
This PR contains some of the style improvements requested:

- Fix spacing on larger displays
- Fix colors for code blocks in light theme
- Fix the table of contents by moving content in separate pages
- Improve dark mode compatibility ( some images have now transparent background and/or have inverted colors in dark mode )
- Replaced an image containing code with a code block

2021-06-19 09:23 UTC, doniks requested changes
Hey @capsia37 I see a couple of content changes. But you don't mention it in your commits. Are those intentional? I mark a few examples with ? below, but there are more

2021-06-19 09:23 UTC, doniks commented on appdev/code-editor.rst
> +Code Editor Integrations
?

2021-06-19 09:23 UTC, doniks commented on appdev/external-docs.rst
> +Documentation
?

2021-06-19 09:23 UTC, doniks commented on appdev/guides/importing-CH-urldispatcher.rst
> +        "hooks": {
?

2021-06-19 09:23 UTC, doniks commented on appdev/index.rst
> -If you have questions that aren't answered in the docs or want to chat with other Ubuntu Touch developers? Join our `app dev Telegram group <https://t.me/UbuntuAppDevEN>`_ or chat with us on the `UBp
?

2021-06-19 10:25 UTC, capsia37 commented
Hello! Yes, it is intentional, the content is the same as before, it just got distributed in pages because of the way that the table of contents works in the theme. When we changed the theme we created some ambiguity in the structure of the table of contents since the headings of the pages are displayed in the right sidebar to reduce the depth of the left sidebar which is now cleaner. But this also caused the left sidebar to group all the pages together instead of grouping them by chapter ( which are listed on the right sidebar ). This changes should bring the structure of the left menu back to what it used to be.

Previous toc:
![Previous](https://user-images.githubusercontent.com/43005909/122639191-cfb2cb00-d0f8-11eb-93c0-831a1666abcc.png)

Current toc:
![Current](https://user-images.githubusercontent.com/43005909/122639194-d6d9d900-d0f8-11eb-89ca-e5da123c2359.png)

Expected toc:
![Expected](https://user-images.githubusercontent.com/43005909/122639217-fa048880-d0f8-11eb-9b33-c4c5b27d2a10.png)

2021-06-22 04:04 UTC, doniks commented
Ah, yes, now I understand. Great, I think independently of adjusting for the theme, this actually makes the docs code a little less spaghetti. Nice!

And wow really nice dark theme support. I love it inverting images :O I didn't know that's possible. Thanks a lot!

2021-06-22 04:04 UTC, doniks approved these changes

2021-06-22 04:05 UTC, merged

2021-06-22 04:45 UTC, doniks commented
@capsia37 I feel we should get your recent style work get highlighted in the next Q&A. 

Firstly, just the revamped 'normal' look in UBports style is worth noting. But also, secondly the dark mode look could be celebrated . However, for the dark mode there is one sore point: the logo on the top left. This doesn't look good. It's very dull. Are you able to adjust this?

2021-06-22 04:45 UTC, doniks commented
![image](https://user-images.githubusercontent.com/26801304/122864742-767baf00-d325-11eb-93c4-90f86de538ea.png)