Remove plasma mobile from docs
ubports/docs.ubports.com pull request #455
Opened 2021-11-01 20:03 UTC by kreatoo

Plasma mobile removed halium support some time ago, so it shouldn't be mentioned in the docs.

2021-11-01 20:16 UTC, istadem2077 requested changes
Add Droidian, since it uses Halium too.

2021-11-04 05:33 UTC, doniks commented
the remark about droidian might be valid. I'm not familiar with it

however, this doesn't have to be done in this same PR. it looks good as is. I'm merging it

maybe @istadem2077 you could even follow up with a PR about Droidian. In that case it would be helpful for me if you could also point out some reference that shows the relation between Droidian and Halium

2021-11-04 05:34 UTC, doniks approved these changes
thanks @kreatoo it's indeed overdue

2021-11-04 05:34 UTC, merged

2021-11-04 05:35 UTC, doniks approved these changes