Update H9_build.rst
ubports/docs.ubports.com pull request #499
Opened 2022-05-04 20:05 UTC by mathew-dennis

adding content related to system-as-root .

2022-06-07 16:04 UTC, abkro reviewed
Small spelling mistake:
to be build as > to be built as

2022-07-25 12:48 UTC, doniks commented
@mathew-dennis are you able to follow up the review?

2022-07-25 13:12 UTC, mathew-dennis commented
> @mathew-dennis are you able to follow up the review?

sorry I missed @abkro 's review, added the change,please review now
and thanks @abkro

2022-07-25 13:27 UTC, doniks requested changes

2022-07-25 13:27 UTC, doniks commented on porting/build_and_boot/H9_build.rst
> +For halium 9, we need the system image to be built as system-as-root (for treble devices it should already be there ). Please check your ''boardconfig.mk'' for the following line, if it's there you c
halium 9 -> Halium 9

"there )" -> "there)" remove extra space

formatting of boardconfig should be with two backticks not two single quotes, ie ``boardconfig`` https://sphinx-tutorial.readthedocs.io/step-1/#code-samples

2022-07-25 13:28 UTC, doniks commented
hey thanks for the quick followup. however, also, sorry, I found a few more points pls check

2022-07-27 18:31 UTC, mathew-dennis commented on porting/build_and_boot/H9_build.rst
> +     /persist
backslashes are needed or we may have to repeat the first line 3 times.

2022-07-27 18:35 UTC, mathew-dennis commented
@doniks done ;-) 

also, could you please check with TheKit before merging, coz when I made this pr ,there was a comment in the porting group that this content is no longer relevant.thanks

2022-07-27 18:52 UTC, doniks commented
> @doniks done ;-)

Awesome. Thanks. 

> 
> also, could you please check with TheKit before merging, coz when I made this pr ,there was a comment in the porting group that this content is no longer relevant.thanks

Of course! :D @NotKit could you weigh in here?

2022-07-27 18:52 UTC, doniks approved these changes

2022-09-18 20:54 UTC, doniks commented
Mhm. We've been sitting on this for a while now. No feedback from notkit, but I also think this is not a very risky change. Let's merge and fix it later if needed

2022-09-18 20:54 UTC, merged