Draft: Porting documentation language reworked
ubports/docs.ubports.com pull request #524
Opened 2022-10-03 02:24 UTC by comradekingu

2022-10-07 10:38 UTC, doniks commented on porting/introduction/Preparations.rst
> +`Pick an Android target device<http://docs.halium.org/en/latest/porting/first-steps.html#pick-an-android-target-device>`_ in the Halium Porting Guide helps you find out if it meets the requirements.
It fails to build here https://ci.ubports.com/blue/organizations/jenkins/docs.ubports.com/detail/PR-524/4/pipeline
Not sure why though :( maybe the deleted space after "device"?

2022-10-07 10:39 UTC, doniks requested changes
doesn't built right now. pls check below (haven't reviewed any further yet)

2022-10-07 10:49 UTC, comradekingu commented on porting/introduction/Preparations.rst
> +`Pick an Android target device<http://docs.halium.org/en/latest/porting/first-steps.html#pick-an-android-target-device>`_ in the Halium Porting Guide helps you find out if it meets the requirements.
```suggestion
`Pick an Android target device <https://docs.halium.org/en/latest/porting/first-steps.html#pick-an-android-target-device>`_ in the Halium Porting Guide helps you find out if it meets the requirements.
```

2022-10-07 11:50 UTC, doniks commented
it has conflicts now

2023-07-23 15:05 UTC, doniks commented
ping?

2023-07-23 15:37 UTC, comradekingu commented
@doniks It stopped complaining (?). Just undid the conflict, and changed the line-shifting around.

2023-07-23 15:45 UTC, doniks commented
still complaining :thinking: 
![image](https://github.com/ubports/docs.ubports.com/assets/26801304/7ec073e5-89d4-4180-923b-cba7c7331761)

2023-07-23 18:53 UTC, comradekingu commented
@doniks You must have missed the "no complaints" merge window X)
It is friendly now, after sending me for a tribute run.

2024-03-24 13:29 UTC, doniks commented
cleaning up old open PR's ... in case you want to refloat this feel free to reopen!

2024-03-24 13:29 UTC, closed without merging